CACHE_DIR ?= $(CURDIR)/.cache/go-build
export GOCACHE := $(CACHE_DIR)

BINDIR ?= $(CURDIR)/bin
BIN ?= $(BINDIR)/globular-installer
CMD_PKG := ./cmd/globular-installer

ASSET_BIN_DIR ?= $(CURDIR)/internal/assets/bin
ASSET_WEBROOT_DIR ?= $(CURDIR)/internal/assets/webroot
ASSET_WEBROOT_MANIFEST ?= $(ASSET_WEBROOT_DIR)/manifest.json
BUNDLE_SRC_BIN ?= $(CURDIR)/../globular/bin
BUNDLE_BINS ?= gateway xds
SERVICES_WEBROOT_ROOT ?= $(CURDIR)/../services/webroot

# Spec authority: registry.yaml declares the canonical package set, and the
# per-package install recipe lives under packages/<name>/specs/ (the metadata
# tree was flattened to the packages repo root — see packages commit
# "flatten metadata/ to repo root"). METADATA_ROOT therefore points at the
# packages repo root, and spec lookups resolve $(METADATA_ROOT)/<name>/specs.
REGISTRY ?= $(CURDIR)/../packages/registry.yaml
METADATA_ROOT ?= $(CURDIR)/../packages
SPEC_DEST_DIR ?= $(CURDIR)/internal/packagecatalog/specs
PACKAGECATALOG_MANIFEST ?= $(CURDIR)/internal/packagecatalog/manifest.json
SYNC_SPEC_KINDS ?= service infrastructure

.PHONY: all build test fmt tidy clean ensure-cache bin bundle bundle-stage sync-specs sync-webroot check-specs check-specs-fixtures check-webroot check-asset-bin

all: build

bin:
	mkdir -p $(BINDIR)

ensure-cache:
	mkdir -p $(CACHE_DIR)

# Build the installer binary (the main package lives under cmd/globular-installer)
build: ensure-cache bin sync-specs sync-webroot
	go build -buildvcs=false -o $(BIN) $(CMD_PKG)

# Optional: build all packages (useful for catching compile errors across the repo)
build-all: ensure-cache
	go build -buildvcs=false ./...

test: ensure-cache
	go test ./...

fmt:
	go fmt ./...

tidy:
	go mod tidy

clean:
	go clean -cache
	rm -rf $(CACHE_DIR) $(BINDIR)

bundle-stage:
	mkdir -p $(ASSET_BIN_DIR)
	@for b in $(BUNDLE_BINS); do \
		if [ ! -f "$(BUNDLE_SRC_BIN)/$$b" ]; then \
			echo "missing binary: $(BUNDLE_SRC_BIN)/$$b" >&2; exit 1; \
		fi; \
		cp -f "$(BUNDLE_SRC_BIN)/$$b" "$(ASSET_BIN_DIR)/$$b"; \
		chmod 0755 "$(ASSET_BIN_DIR)/$$b"; \
	done

bundle: bundle-stage build

# sync-specs rebuilds the embedded installer package catalog from the package
# authority: registry.yaml defines the canonical package set, and
# metadata/<name>/specs/ holds the install recipe. Command packages are skipped
# because they do not ship *_service.yaml specs for Day-0 service installation.
sync-specs:
	@[ -f "$(REGISTRY)" ] || { echo "ERROR: registry not found at $(REGISTRY)" >&2; exit 1; }
	@[ -d "$(METADATA_ROOT)" ] || { echo "ERROR: metadata root not found at $(METADATA_ROOT)" >&2; exit 1; }
	mkdir -p "$(SPEC_DEST_DIR)"
	rm -f "$(SPEC_DEST_DIR)"/*_service.yaml
	@found=0; missing=0; skipped=0; \
	for name in $$(python3 -c 'import sys,yaml; data=yaml.safe_load(open(sys.argv[1])) or {}; allowed=set(sys.argv[2].split()); [print(pkg["name"]) for pkg in data.get("packages", []) if pkg.get("kind") in allowed and pkg.get("name")]' "$(REGISTRY)" "$(SYNC_SPEC_KINDS)"); do \
		specs=$$(find "$(METADATA_ROOT)/$$name/specs" -maxdepth 1 -name '*_service.yaml' -type f 2>/dev/null); \
		if [ -n "$$specs" ]; then \
			for src in $$specs; do \
				dst="$(SPEC_DEST_DIR)/$$(basename "$$src")"; \
				{ \
					printf '%s\n' '# Generated mirror of packages/registry.yaml.'; \
					printf '%s\n' '# Do not edit this file directly.'; \
					cat "$$src"; \
				} > "$$dst"; \
			done; \
			found=$$(( $$found + $$(printf '%s\n' "$$specs" | sed '/^$$/d' | wc -l) )); \
		elif [ -d "$(METADATA_ROOT)/$$name" ]; then \
			echo "ERROR: $$name ($(SYNC_SPEC_KINDS)) missing *_service.yaml under metadata/$$name/specs/" >&2; \
			missing=$$(( $$missing + 1 )); \
		fi; \
	done; \
	for name in $$(python3 -c 'import sys,yaml; data=yaml.safe_load(open(sys.argv[1])) or {}; [print(pkg["name"]) for pkg in data.get("packages", []) if pkg.get("kind") == "command" and pkg.get("name")]' "$(REGISTRY)"); do \
		skipped=$$(( $$skipped + 1 )); \
	done; \
	if [ $$missing -gt 0 ]; then \
		echo "ERROR: $$missing runtime package(s) missing embedded specs." >&2; \
		exit 1; \
	fi; \
	python3 -c 'import hashlib, json, pathlib, sys, yaml; reg=pathlib.Path(sys.argv[1]); manifest=pathlib.Path(sys.argv[2]); allowed=set(sys.argv[3].split()); data=yaml.safe_load(reg.read_text()) or {}; entries=[pkg for pkg in data.get("packages", []) if pkg.get("kind") in allowed and pkg.get("name")]; manifest.write_text(json.dumps({"schema":"globular.packagecatalog.mirror/v1","source":"packages/registry.yaml","mirror_dir":"globular-installer/internal/packagecatalog/specs","registry_sha256":hashlib.sha256(reg.read_bytes()).hexdigest(),"package_count":len(entries)}, indent=2) + "\n")' "$(REGISTRY)" "$(PACKAGECATALOG_MANIFEST)" "$(SYNC_SPEC_KINDS)"; \
	echo "sync-specs: $$found specs synced to $(SPEC_DEST_DIR) ($$skipped command packages skipped)"

# sync-webroot rebuilds the installer fallback webroot mirror from the authored
# services/webroot source. This mirror supports source-tree/developer installs
# when a release tarball webroot is not present; it is never hand-authored.
sync-webroot:
	@[ -d "$(SERVICES_WEBROOT_ROOT)" ] || { echo "ERROR: services webroot not found at $(SERVICES_WEBROOT_ROOT)" >&2; exit 1; }
	mkdir -p "$(ASSET_WEBROOT_DIR)"
	find "$(ASSET_WEBROOT_DIR)" -mindepth 1 ! -name 'manifest.json' -exec rm -rf {} +
	cp -a "$(SERVICES_WEBROOT_ROOT)/." "$(ASSET_WEBROOT_DIR)/"
	@python3 -c 'import hashlib, json, pathlib, sys; src=pathlib.Path(sys.argv[1]); manifest=pathlib.Path(sys.argv[2]); files={}; agg=hashlib.sha256(); \
paths=sorted([p for p in src.rglob("*") if p.is_file()]); \
[agg.update(str(p.relative_to(src)).encode()) or agg.update(b"\0") or agg.update(p.read_bytes()) or agg.update(b"\0") or files.__setitem__(str(p.relative_to(src)), hashlib.sha256(p.read_bytes()).hexdigest()) for p in paths]; \
manifest.write_text(json.dumps({"schema":"globular.webroot.mirror/v1","source":"services/webroot","mirror_dir":"globular-installer/internal/assets/webroot","source_sha256":agg.hexdigest(),"files":files}, indent=2) + "\n")' "$(SERVICES_WEBROOT_ROOT)" "$(ASSET_WEBROOT_MANIFEST)"
	@echo "sync-webroot: mirrored $(SERVICES_WEBROOT_ROOT) -> $(ASSET_WEBROOT_DIR)"

check-webroot:
	@[ -d "$(SERVICES_WEBROOT_ROOT)" ] || { echo "ERROR: services webroot not found at $(SERVICES_WEBROOT_ROOT)" >&2; exit 1; }
	@[ -d "$(ASSET_WEBROOT_DIR)" ] || { echo "ERROR: installer webroot mirror not found at $(ASSET_WEBROOT_DIR)" >&2; exit 1; }
	@python3 -c 'exec("""import hashlib, json, sys\nfrom pathlib import Path\nsrc=Path(sys.argv[1]); dst=Path(sys.argv[2]); manifest_path=Path(sys.argv[3])\nif not manifest_path.is_file():\n    print(f\"MISSING: {manifest_path} (installer webroot mirror manifest missing)\", file=sys.stderr); sys.exit(1)\nmanifest=json.loads(manifest_path.read_text())\nif manifest.get(\"schema\") != \"globular.webroot.mirror/v1\" or manifest.get(\"source\") != \"services/webroot\" or manifest.get(\"mirror_dir\") != \"globular-installer/internal/assets/webroot\":\n    print(f\"STALE: {manifest_path} (mirror metadata mismatch)\", file=sys.stderr); sys.exit(1)\nsource_files=sorted([p for p in src.rglob(\"*\") if p.is_file()])\nmirror_files=sorted([p for p in dst.rglob(\"*\") if p.is_file() and p.name != \"manifest.json\"])\nsrel={str(p.relative_to(src)):p for p in source_files}; mrel={str(p.relative_to(dst)):p for p in mirror_files}\nif set(srel) != set(mrel):\n    print(f\"STALE: webroot file set mismatch source={sorted(srel)} mirror={sorted(mrel)}\", file=sys.stderr); sys.exit(1)\nagg=hashlib.sha256(); files=manifest.get(\"files\") or {}\nfor name in sorted(srel):\n    raw=srel[name].read_bytes(); digest=hashlib.sha256(raw).hexdigest(); agg.update(name.encode()); agg.update(b\"\\0\"); agg.update(raw); agg.update(b\"\\0\")\n    if mrel[name].read_bytes() != raw:\n        print(f\"STALE: installer webroot mirror drift for {name}\", file=sys.stderr); sys.exit(1)\n    if files.get(name) != digest:\n        print(f\"STALE: manifest digest mismatch for {name}\", file=sys.stderr); sys.exit(1)\nif manifest.get(\"source_sha256\") != agg.hexdigest():\n    print(f\"STALE: {manifest_path} source_sha256 mismatch\", file=sys.stderr); sys.exit(1)\nprint(\"check-webroot: installer webroot mirror matches services/webroot\")""")' "$(SERVICES_WEBROOT_ROOT)" "$(ASSET_WEBROOT_DIR)" "$(ASSET_WEBROOT_MANIFEST)"

check-asset-bin:
	@[ -d "$(ASSET_BIN_DIR)" ] || { echo "ERROR: installer asset bin dir not found at $(ASSET_BIN_DIR)" >&2; exit 1; }
	@python3 -c 'exec("""import sys\nfrom pathlib import Path\nroot=Path(sys.argv[1]); allowed={\".gitkeep\",\"check-ingress.sh\"}; bad=[]\nfor p in sorted(root.iterdir()):\n    if p.name in allowed:\n        continue\n    if p.is_file():\n        raw=p.read_bytes()[:4]\n        if raw.startswith(b\"\\x7fELF\") or raw.startswith(b\"MZ\"):\n            bad.append(f\"compiled binary not allowed: {p}\")\n        elif p.suffix not in {\".sh\",\".txt\",\".md\",\".json\"}:\n            bad.append(f\"unexpected installer helper asset: {p}\")\nif bad:\n    print(\"\\n\".join(bad), file=sys.stderr); sys.exit(1)\nprint(\"check-asset-bin: installer asset bin contains helper assets only\")""")' "$(ASSET_BIN_DIR)"

# check-specs verifies that installer embedded mirrors match their authorities.
check-specs: check-webroot check-asset-bin
	@[ -f "$(REGISTRY)" ] || { echo "ERROR: registry not found at $(REGISTRY)" >&2; exit 1; }
	@[ -d "$(METADATA_ROOT)" ] || { echo "ERROR: metadata root not found at $(METADATA_ROOT)" >&2; exit 1; }
	@python3 -c 'exec("""import hashlib, json, sys, yaml\nfrom pathlib import Path\nHEADER = \"# Generated mirror of packages/registry.yaml.\\n# Do not edit this file directly.\\n\"\nreg = Path(sys.argv[1])\nmeta = Path(sys.argv[2])\ndest = Path(sys.argv[3])\nmanifest_path = Path(sys.argv[4])\nallowed = set(sys.argv[5].split())\ndata = yaml.safe_load(reg.read_text()) or {}\nexpected = {}\nmissing = stale = extra = 0\nfor pkg in data.get(\"packages\", []):\n    if pkg.get(\"kind\") not in allowed or not pkg.get(\"name\"):\n        continue\n    name = pkg[\"name\"]\n    spec_dir = meta / name / \"specs\"\n    specs = sorted(spec_dir.glob(\"*_service.yaml\")) if spec_dir.is_dir() else []\n    if len(specs) != 1:\n        print(f\"MISSING: {name} requires exactly one *_service.yaml under metadata/{name}/specs\")\n        missing += 1\n        continue\n    src = specs[0]\n    expected[src.name] = src\n    target = dest / src.name\n    if not target.is_file():\n        print(f\"MISSING: {src.name} (registry package {name} not in installer)\")\n        missing += 1\n        continue\n    content = target.read_text()\n    if not content.startswith(HEADER) or content[len(HEADER):] != src.read_text():\n        print(f\"STALE: {src.name} (differs from metadata/{name}/specs or is missing mirror header)\")\n        stale += 1\nfor target in sorted(dest.glob(\"*_service.yaml\")):\n    if target.name not in expected:\n        print(f\"EXTRA: {target.name} (not present in registry-backed metadata specs)\")\n        extra += 1\nif not manifest_path.is_file():\n    print(f\"MISSING: {manifest_path} (installer packagecatalog manifest missing)\")\n    missing += 1\nelse:\n    manifest = json.loads(manifest_path.read_text())\n    digest = hashlib.sha256(reg.read_bytes()).hexdigest()\n    if manifest.get(\"schema\") != \"globular.packagecatalog.mirror/v1\" or manifest.get(\"source\") != \"packages/registry.yaml\" or manifest.get(\"mirror_dir\") != \"globular-installer/internal/packagecatalog/specs\" or manifest.get(\"registry_sha256\") != digest or manifest.get(\"package_count\") != len(expected):\n        print(f\"STALE: {manifest_path} (registry digest / package count mismatch)\", file=sys.stderr)\n        stale += 1\nif stale or missing or extra:\n    print(f\"ERROR: {stale} stale + {missing} missing + {extra} extra specs. Run make sync-specs to fix.\", file=sys.stderr)\n    sys.exit(1)\nprint(\"check-specs: installer packagecatalog and fallback assets match their authorities\")""")' "$(REGISTRY)" "$(METADATA_ROOT)" "$(SPEC_DEST_DIR)" "$(PACKAGECATALOG_MANIFEST)" "$(SYNC_SPEC_KINDS)"

check-specs-fixtures:
	@tmp=$$(mktemp -d); trap 'rm -rf "$$tmp"' EXIT; \
	reg="$$tmp/registry.yaml"; meta="$$tmp/metadata"; dest="$$tmp/specs"; \
	mkdir -p "$$meta/svc/specs" "$$meta/cmd" "$$dest"; \
	printf '%s\n' 'packages:' '  - name: svc' '    kind: service' '  - name: cmd' '    kind: command' > "$$reg"; \
	printf '%s\n' 'metadata: {name: svc, kind: service}' > "$$meta/svc/specs/svc_service.yaml"; \
	$(MAKE) --no-print-directory REGISTRY="$$reg" METADATA_ROOT="$$meta" SPEC_DEST_DIR="$$dest" check-specs >/dev/null; \
	echo "fixture: command-only package with no spec accepted"; \
	rm -f "$$meta/svc/specs/svc_service.yaml"; \
	if $(MAKE) --no-print-directory REGISTRY="$$reg" METADATA_ROOT="$$meta" SPEC_DEST_DIR="$$dest" check-specs >/dev/null 2>&1; then \
		echo "ERROR: fixture expected missing service spec to fail" >&2; exit 1; \
	fi; \
	echo "fixture: missing service spec fails"; \
	printf '%s\n' 'metadata: {name: svc, kind: service}' > "$$meta/svc/specs/svc_service.yaml"; \
	$(MAKE) --no-print-directory REGISTRY="$$reg" METADATA_ROOT="$$meta" SPEC_DEST_DIR="$$dest" sync-specs >/dev/null; \
	printf '%s\n' 'metadata: {name: ghost, kind: service}' > "$$dest/ghost_service.yaml"; \
	if $(MAKE) --no-print-directory REGISTRY="$$reg" METADATA_ROOT="$$meta" SPEC_DEST_DIR="$$dest" check-specs >/dev/null 2>&1; then \
		echo "ERROR: fixture expected stale extra spec to fail" >&2; exit 1; \
	fi; \
	echo "fixture: stale extra internal spec fails"
